name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
    name: Pipeline de CI
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo o código
        uses: actions/checkout@v4.2.2
      - name: Autenticação no Docker Hub
        uses: docker/login-action@v3.4.0
        with:
          username: leandromelo99
          password: Le@102030
          
    
